name: Build Backend
on:
  push:
    branches: [main, dev*]
  pull_request:
    branches: [main, dev*]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker build --file ./source/backend/coach/Dockerfile ./source/backend/coach
          docker build --file ./source/backend/school/Dockerfile ./source/backend/school
          docker build --file ./source/backend/player/Dockerfile ./source/backend/player
          docker build --file ./source/backend/university/Dockerfile ./source/backend/university
