name: Frontend CICD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  id-token: write
  contents: read
env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
          aws-region: us-west-2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build Frontend with NPM
        working-directory: source/frontend
        run: |
          npm ci
          npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Frontend to S3
        working-directory: source/frontend
        run: |
          aws s3 sync ./dist "s3://${ENVIRONMENT}-fia7-frontend" --delete
        env:
          AWS_DEFAULT_REGION: us-west-2
